import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/header/Header'

const inter = Inter({
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700'],
})

export const metadata: Metadata = {
    title: 'E-Store',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en' className='min-h-screen'>
            <body
                className={`${inter.className}  antialiased min-h-screen flex justify-center`}
            >
                <div className='w-360'>
                    <Header />
                    <main>{children}</main>
                </div>
            </body>
        </html>
    )
}
